endpoint: wss://polkadot-bridge-hub-rpc.polkadot.io
mock-signature-host: true
block: ${env.POLKADOT_BRIDGEHUB_BLOCK_NUMBER}
db: ./db.sqlite
wasm-override: wasms/bridge-hub-polkadot_v1.9.1.wasm

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
